In [1]:
import numpy as np

In [3]:
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]

In [4]:
arr = np.array(list)

In [5]:
print(arr*4)

[ 80 108  36  48 124  68  16 200 156 140]


In [6]:
print(np.mean(arr))

24.4


In [7]:
print(np.median(arr))

23.5


In [8]:
print(np.std(arr))

13.828955130450023


In [11]:
print(np.argmin(arr))
print(arr[np.argmin(arr)])

6
4


In [12]:
print(np.argmax(arr))
print(arr[np.argmax(arr)])

7
50


In [13]:
print(np.min(arr))

4


In [14]:
print(np.max(arr))

50


In [18]:
matrix = [
    [5, 12, 17, 9],
    [8, 21, 14, 3], 
    [6, 13, 19, 11]
]
print(np.shape(matrix))

rows = np.shape(matrix)[0]
columns = np.shape(matrix)[1]

print(f"rows: {rows}")
print(f"columns: {columns}")

(3, 4)
rows: 3
columns: 4


In [19]:
array = np.array(matrix)

[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [21]:
print(array[:, 2])

[17 14 19]


In [22]:
print(array[1])

[ 8 21 14  3]


In [27]:
print(array*2)

[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [28]:
print(np.mean(array, axis = 0))

[ 6.33333333 15.33333333 16.66666667  7.66666667]


In [29]:
print(np.mean(array))

11.5


In [31]:
# max across rows
print(np.max(array, axis = 1))

[17 21 19]


In [32]:
# max across columns
print(np.max(array, axis = 0))

[ 8 21 19 11]


In [34]:
arr = array.flatten()
print(arr)

[ 5 12 17  9  8 21 14  3  6 13 19 11]


In [35]:
print(np.argmin(arr))

7


In [36]:
print(np.argmax(arr))

5


In [38]:
print(np.unravel_index(np.argmin(arr), array.shape))
print(np.unravel_index(np.argmax(arr), array.shape))

(np.int64(1), np.int64(3))
(np.int64(1), np.int64(1))


In [39]:
newArr = array[array > 15]
print(newArr)

[17 21 19]


In [40]:
print(np.sort(array))

[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [42]:
arr = np.array([
    [2, 3, 5],
    [14, 6, 8],
    [11, 13, 17],
    [7, 10, 13]
])

def is_prime(n):
    if n == 0 or n == 1:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

def row_prime(array):
    result = []
    for row in array:
        if any(is_prime(x) for x in row):
            result.append(row)
    return np.array(result)

print(row_prime(arr))

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [56]:
def checkerboard():
    board = np.zeros((8, 8), dtype=int)
    
    for i in range(8):
        board[i, i % 2::2] = 1
        
    return board

In [57]:
board_array = checkerboard()
print(board_array)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [61]:
def reverse_checkerboard():
    board = np.zeros((8, 8), dtype=int)
    
    for i in range(8):
        board[i, (i + 1) % 2::2] = 1
        
    return board

In [62]:
reverse_array = reverse_checkerboard()
print(reverse_array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [67]:
def expansion(arr, spaces):
    result = np.empty(arr.shape, dtype=object)
    i = 0
    while i < len(arr):
        word = arr[i]
        expanded = ""
        j = 0
        while j < len(word):
            expanded += word[j]
            if j != len(word) - 1:
                k = 0
                while k < spaces:
                    expanded += " "
                    k += 1
            j += 1
        result[i] = expanded
        i += 1
    return result

universe = np.array(['galaxy', 'clusters'])
expansion(universe, 1)

array(['g a l a x y', 'c l u s t e r s'], dtype=object)

In [70]:
def second_brightest(s):
    rows = arr.shape[0]
    result = np.zeros(rows, dtype=int)
    
    for i in range(rows):
        row = arr[i]
        largest = row[0]
        for val in row:
            if val > largest:
                largest = val
        second = None
        for val in row:
            if val != largest:
                if (second is None) or (val > second):
                    second = val      
        result[i] = second
    return result

stars = np.random.randint(500, 2000, (5, 5))
second_brightest(stars)

array([ 3,  8, 13, 10])